import coreWebVitals from "eslint-config-next/core-web-vitals";
import typescript from "eslint-config-next/typescript";

const eslintConfig = [
  ...coreWebVitals,
  ...typescript,
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      ".contentlayer/**",
      ".velite/**",
      "public/**/*.js", // Minified vendor scripts
      "next-env.d.ts", // Auto-generated by Next.js
      "tailwindcss.config.js", // Legacy config with require()
    ],
  },
];

export default eslintConfig;
