import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      ".contentlayer/**",
      ".velite/**",
      "public/**/*.js", // Minified vendor scripts
      "next-env.d.ts", // Auto-generated by Next.js
      "tailwindcss.config.js", // Legacy config with require()
    ],
  },
];

export default eslintConfig;
